name 'chatops_deployer'
maintainer 'Emil Soman'
maintainer_email 'emil@codemancers.com'
license 'MIT'
description 'Installs/Configures chatops_deployer'
long_description 'Installs/Configures chatops_deployer'
version '0.1.4'
depends 'docker', '~> 2.7.1'
depends 'chef-vault'
depends 'ruby_build'
depends 'hostsfile'
depends 'supervisor'
depends 'apt'
depends 'build-essential'
depends 'nodejs'
depends 'openssl'
